# FORMAT
# triggers: dict
#   command_name: list[str] - list of triggers, what be used in scope with /command
#     - command_trigger
# commands_list: list[str]
#   - name: str - Name what were visible in telegram / hint
# echo_commands: list[Obj]
#   - command: Obj
#       name: str
#       message: str - message code in lang files
#       times: list[obj] - default = []
#         - key: str - default "working_status"
#         - time: str - time code in times.yaml
#       images: Obj
#         caption_above: bool - default = False
#         files: list[str]
#           - image file src/res/...

triggers:
  cards:
    - cards
    - card
    - карты
  services:
    - services
    - srcs
    - услуги
  help:
    - help
    - начать
    - помощь
    - хелп
    - команды
    - комманды
    - список
    - помоги
    - я долбаеб
    - я долбоебка
    - я долбоёб
    - я долбоёбка
    - я долбаебка
    - я долбаёбка
  kek:
    - кек
    - kek
  index:
    - index
    - zip
    - postal
    - index
    - индекс
  address:
    - address
    - adress
    - addres
    - adres
    - адрес
    - адресс
    - адресочек
  commandant:
    - commandant
    - comandant
    - comandat
    - коменда
    - комендант
    - командант
    - командантка
    - комменда
    - коммендант
    - коммандант
    - коммандантка
  director:
    - director
    - заведующий
    - заведующая
    - завед
    - заведа
  vost:
    - vostochka
    - vost
    - восточка
  jko:
    - jko
    - hud
    - жко
    - жк
    - жилищно коммунальный
    - жилищно коммунальный отдел
    - жилищно-коммунальный отдел
  hr:
    - hr
    - human resources
    - отдел кадров
  ed:
    - unified deans
    - ed
    - единый деканат
    - ед
  polyclinic:
    - polyclinic
    - поликлиника
    - поликлинника
  accounting:
    - бухгалтерия
    - accounting
  library:
    - library
    - библиотека
  buffet:
    - bufet
    - buffet
    - буфет
  canteen:
    - canteen
    - столовка
    - столовая
  week:
    - week
    - неделя
  soft:
    - soft
    - софт
    - программы
    - программное обеспечение
    - по
  shower:
    - shower
    - душ
  kitchen:
    - kitchen
    - кухня
    - кухни
  laundress:
    - laundress
    - прачка
  linen:
    - linen
    - linen exchange
    - обмен белья
    - бельё
    - обменка
  dean:
    - деканат
    - факультет
    - декан
  deanit:
    - it deans
    - факультет ит
    - фак ит
    - деканат ит
  deanrit:
    - rit deans
    - факультет рит
    - фак рит
    - деканат рит
  deannacs:
    - nacs deans
    - факультет сисс
    - фак сисс
    - деканат сисс
  deancais:
    - cais deans
    - факультет кииб
    - фак кииб
    - деканат кииб
  deandeamc:
    - deamc deans
    - факультет цэимк
    - фак цэимк
    - деканат цэимк
  deanforeign:
    - иностранный отдел
    - иностранный деканат
    - иностраный отдел
    - иностраный деканат
    - ин отдел
    - инотдел
    - индеканат
    - ин деканат
  incorrect_director:
    - заведущий
    - заведущая
  depritres:
    - department of res
    - department res
    - res department
    - кафедра ртс
  depritreac:
    - department of reac
    - department reac
    - reac department
    - кафедра рос
  depritelect:
    - department of elect
    - department elect
    - elect department
    - кафедра электроники
  deprittasb:
    - department of tasb
    - department tasb
    - tasb department
    - кафедра тизв
  depritratsan:
    - department of ratsan
    - department ratsan
    - ratsan department
    - кафедра сисрт
  deprittec:
    - department of tec
    - department tec
    - tec department
    - кафедра тэц
  depritphys:
    - department of phys
    - department phys
    - phys department
    - кафедра физики
  depritteaa:
    - department of teaa
    - department teaa
    - teaa department
    - кафедра тэдиа
  depitmcait:
    - department of mcait
    - department mcait
    - mcait department
    - кафедра мкиит
  depitmcis:
    - department of cis
    - department cis
    - cis department
    - кафедра кис
  depitnitas:
    - department of nitas
    - department nitas
    - nitas department
    - кафедра ситис
  depitma:
    - department of mathanalysis
    - department mathanalysis
    - mathanalysis department
    - кафедра матанализ
  depitinf:
    - department of informatics
    - department informatics
    - informatics department
    - кафедра информатика
  depitpe:
    - department of physedu
    - department physedu
    - physedu department
    - кафедра физвосп
  depitaai:
    - department of aai
    - department aai
    - aai department
    - кафедра пии
  depitsp:
    - department of sp
    - department sp
    - sp department
    - кафедра сп
  depnacsmts:
    - department of mts
    - department mts
    - mts department
    - кафедра мтс
  depnacsgts:
    - department of gts
    - department gts
    - gts department
    - кафедра нтс
  depnacsgnass:
    - department of nass
    - department nass
    - nass department
    - кафедра ссиск
  depnacsmsami:
    - department of msami
    - department msami
    - msami department
    - кафедра мсиии
  depnacsgtc:
    - department of gtc
    - department gtc
    - gtc department
    - кафедра отс
  depcaisedet:
    - department of edet
    - department edet
    - edet department
    - кафедра тэод
  depcaisis:
    - department of is
    - department is
    - is department
    - кафедра иб
  depcaisismaa:
    - department of ismaa
    - department ismaa
    - ismaa department
    - кафедра исуиа
  depcaistcs:
    - department of tcs
    - department tcs
    - tcs department
    - кафедра бтк
  depcaisptaam:
    - department of ptaam
    - department ptaam
    - ptaam department
    - кафедра твипм
  depcaiselsap:
    - department of elsap
    - department elsap
    - elsap department
    - кафедра эбжиэ
  depcaisbmt:
    - department of bmt
    - department bmt
    - bmt department
    - кафедра овп
  depdeamcdat:
    - department of dat
    - department dat
    - dat department
    - кафедра цтр
  depdeamcsrapr:
    - department of srapr
    - department srapr
    - srapr department
    - кафедра срисо
  depdeamcdemabt:
    - department of demabt
    - department demabt
    - demabt department
    - кафедра цэуибт
  depdeamcphaic:
    - department of phaic
    - department phaic
    - phaic department
    - кафедра фиимк
  depdeamcfor:
    - department of for
    - department for
    - for department
    - кафедра ино
  depdeamcbcs:
    - department of bcs
    - department bcs
    - bcs department
    - кафедра би
  hype_collector_greeting:
    - хайп коллектор
commands_list:
  - cards
  - index
  - address
  - director
  - jko
  - hr
  - polyclinic
  - library
  - services
  - vost
  - buffet
  - canteen
  - week
  - soft
  - shower
  - kitchen
  - laundress
  - linen
  - accounting
  - help
  - ed
  - deanit
  - deanrit
  - deannacs
  - deancais
  - deandeamc
  - deanforeign
echo_commands:
  - name: help
    message: echo_commands.help
  - name: index
    message: echo_commands.index
  - name: address
    message: echo_commands.address
  - name: director
    message: echo_commands.director
    times:
      - time: dorm.director
  - name: commandant
    message: echo_commands.commandant
  - name: jko
    message: echo_commands.jko
    times:
      - time: university.jko
  - name: hr
    message: echo_commands.hr
    times:
      - time: university.hr.working
      - key: working_status_certificate
        time: university.hr.certificate
  - name: soft
    message: echo_commands.soft
  - name: library
    message: echo_commands.library
    times:
      - time: university.library.working
      - key: working_status_clients
        time: university.library.clients
  - name: shower
    message: echo_commands.shower
    times:
      - time: dorm.shower
  - name: kitchen
    message: echo_commands.kitchen
    times:
      - time: dorm.kitchen
  - name: polyclinic
    message: echo_commands.polyclinic
    times:
      - time: polyclinic
  - name: accounting
    message: echo_commands.accounting
    times:
      - time: university.accounting
  - name: dean
    message: echo_commands.deanery.default
  - name: ed
    message: echo_commands.deanery.ed
    times:
      - time: university.deans.ed
  - name: it
    message: echo_commands.deanery.it
    times:
      - time: university.deans.it
  - name: rit
    message: echo_commands.deanery.rit
    times:
      - time: university.deans.rit
  - name: nacs
    message: echo_commands.deanery.nacs
    times:
      - time: university.deans.nacs
  - name: cais
    message: echo_commands.deanery.cais
    times:
      - time: university.deans.cais
  - name: deamc
    message: echo_commands.deanery.deamc
    times:
      - time: university.deans.deamc
  - name: deanforeign
    message: echo_commands.deanery.foreign
    times:
      - time: university.deans.foreign
  - name: vost
    message: echo_commands.cafe_vost
    times:
      - time: university.cafe.vost
    images:
      caption_above: true
      files:
        - src/res/images/cafe_vost.jpg
  - name: buffet
    message: echo_commands.cafe_buffet
    times:
      - key: working_status_a
        time: university.cafe.buffet.a
      - key: working_status_n
        time: university.cafe.buffet.n
    images:
      caption_above: true
      files:
        - src/res/images/cafe_buffet.jpg
  - name: canteen
    message: echo_commands.cafe_canteen
    times:
      - time: university.cafe.canteen
    images:
      caption_above: true
      files:
        - src/res/images/canteen/1.jpg
        - src/res/images/canteen/2.jpg
  - name: linen
    message: echo_commands.linen
    times:
      - time: dorm.linen
    images:
      caption_above: true
      files:
        - src/res/images/linen.jpg
  - name: laundress
    message: echo_commands.laundress
    times:
      - time: laundress
    images:
      files:
        - src/res/images/laundress/1.jpg
        - src/res/images/laundress/2.jpg
  - name: cards
    message: echo_commands.cards
    images:
      files:
        - src/res/images/cards/1.jpg
        - src/res/images/cards/2.jpg
        - src/res/images/cards/3.jpg
        - src/res/images/cards/4.jpg
        - src/res/images/cards/5.jpg
        - src/res/images/cards/6.jpg
        - src/res/images/cards/7.jpg
        - src/res/images/cards/8.jpg
        - src/res/images/cards/9.jpg
        - src/res/images/cards/10.jpg
  - name: incorrect_director
    message: echo_commands.incorrect_director
  - name: deanit
    message: echo_commands.deanery.it
    times:
      - time: university.deans.it
  - name: deanrit
    message: echo_commands.deanery.rit
    times:
      - time: university.deans.rit
  - name: deannacs
    message: echo_commands.deanery.nacs
    times:
      - time: university.deans.nacs
  - name: deancais
    message: echo_commands.deanery.cais
    times:
      - time: university.deans.cais
  - name: deandeamc
    message: echo_commands.deanery.deamc
  - name: deanforeign
    message: echo_commands.deanery.foreign
    times:
      - time: university.deans.foreign
  - name: depritres
    message: echo_commands.departments.rit.res
  - name: depritreac
    message: echo_commands.departments.rit.reac
  - name: depritelect
    message: echo_commands.departments.rit.electronics
  - name: deprittasb
    message: echo_commands.departments.rit.tasb
  - name: depritratsan
    message: echo_commands.departments.rit.ratsan
  - name: deprittec
    message: echo_commands.departments.rit.tec
  - name: depritphys
    message: echo_commands.departments.rit.physics
  - name: depritteaa
    message: echo_commands.departments.rit.teaa
  - name: depitmcait
    message: echo_commands.departments.it.mcait
  - name: depitmcis
    message: echo_commands.departments.it.cis
  - name: depitnitas
    message: echo_commands.departments.it.nitas
  - name: depitma
    message: echo_commands.departments.it.ma
  - name: depitinf
    message: echo_commands.departments.it.informatics
  - name: depitpe
    message: echo_commands.departments.it.pe
  - name: depitaai
    message: echo_commands.departments.it.aai
  - name: depitsp
    message: echo_commands.departments.it.sp
  - name: depnacsmts
    message: echo_commands.departments.nacs.mts
  - name: depnacsgts
    message: echo_commands.departments.nacs.gts
  - name: depnacsgnass
    message: echo_commands.departments.nacs.gnass
  - name: depnacsmsami
    message: echo_commands.departments.nacs.msami
  - name: depnacsgtc
    message: echo_commands.departments.nacs.gtc
  - name: depcaisedet
    message: echo_commands.departments.cais.edet
  - name: depcaisis
    message: echo_commands.departments.cais.is
  - name: depcaisismaa
    message: echo_commands.departments.cais.ismaa
  - name: depcaistcs
    message: echo_commands.departments.cais.tcs
  - name: depcaisptaam
    message: echo_commands.departments.cais.ptaam
  - name: depcaiselsap
    message: echo_commands.departments.cais.elsap
  - name: depcaisbmt
    message: echo_commands.departments.cais.bmt
  - name: depdeamcdat
    message: echo_commands.departments.deamc.dat
  - name: depdeamcsrapr
    message: echo_commands.departments.deamc.srapr
  - name: depdeamcdemabt
    message: echo_commands.departments.deamc.demabt
  - name: depdeamcphaic
    message: echo_commands.departments.deamc.phaic
  - name: depdeamcfor
    message: echo_commands.departments.deamc.for
  - name: depdeamcbcs
    message: echo_commands.departments.deamc.bcs